### ISSUE TITLE
Package this better

### ISSUE THREAD

**Issue by andrewthetechie** [riptidewave93/DO-AutoVPN#3]
This should be packaged to pip so it can autoinstall dependencies

**Comment by andrewthetechie** [comment]
https://github.com/riptidewave93/DO-AutoVPN/pull/5

**Comment by riptidewave93** [comment]
Thanks for the PR!

**Comment by andrewthetechie** [comment]
This should not be closed. This still could use much better packaging.

My suggestion would be to get this into pip. Happy to help get it working via setuptools

**Comment by riptidewave93** [comment]
@andrewthetechie Reopened per request. I am not opposed to packaging this, but before that I would like to work on resolving the other issues in this repo.

**Comment by andrewthetechie** [comment]
Yup, this should be part of the "endgame" for this.
